// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-F237DtoE2-rgs6Ded5iwWgOmp5Wfi7o',
    appId: '1:844175382668:web:7fabf409305cdd5f5b43a9',
    messagingSenderId: '844175382668',
    projectId: 'authexample1-eab2a',
    authDomain: 'authexample1-eab2a.firebaseapp.com',
    storageBucket: 'authexample1-eab2a.firebasestorage.app',
    measurementId: 'G-PPLEBYH7L9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx7K7MJCVcFzFIC9z09BOn1YNQS01bJf8',
    appId: '1:844175382668:android:18f96f738149542b5b43a9',
    messagingSenderId: '844175382668',
    projectId: 'authexample1-eab2a',
    storageBucket: 'authexample1-eab2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFH_GbZNMbzvVB6eGEGkXKxkhLYvmtFFE',
    appId: '1:844175382668:ios:c5f94d0185fbba525b43a9',
    messagingSenderId: '844175382668',
    projectId: 'authexample1-eab2a',
    storageBucket: 'authexample1-eab2a.firebasestorage.app',
    iosBundleId: 'com.example.authExample1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFH_GbZNMbzvVB6eGEGkXKxkhLYvmtFFE',
    appId: '1:844175382668:ios:c5f94d0185fbba525b43a9',
    messagingSenderId: '844175382668',
    projectId: 'authexample1-eab2a',
    storageBucket: 'authexample1-eab2a.firebasestorage.app',
    iosBundleId: 'com.example.authExample1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-F237DtoE2-rgs6Ded5iwWgOmp5Wfi7o',
    appId: '1:844175382668:web:7f0c6d7e305ff3f65b43a9',
    messagingSenderId: '844175382668',
    projectId: 'authexample1-eab2a',
    authDomain: 'authexample1-eab2a.firebaseapp.com',
    storageBucket: 'authexample1-eab2a.firebasestorage.app',
    measurementId: 'G-M1YFNXZYK0',
  );
}
